services:
  # --- Laravel API ---
  - type: web
    name: recruit-api
    runtime: docker
    dockerfilePath: ./Dockerfile.prod
    dockerContext: .
    rootDir: backend
    plan: free
    envVars:
      - key: APP_NAME
        value: "Recruit Portfolio"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        value: "base64:Kk6FYjOMKLlSvB2w8ttabWVH6bQUIvS7ZEwJcxlPErg="
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: recruit-db
          property: connectionString
      - key: MAIL_MAILER
        value: log
      - key: CACHE_STORE
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: SANCTUM_STATEFUL_DOMAINS
        value: "*.vercel.app,yohei0819.github.io"
      - key: FRONTEND_URL
        value: "https://frontend-yohei0819.vercel.app"
      - key: APP_URL
        value: "https://recruit-api-sop3.onrender.com"
      - key: ADMIN_URL
        value: "https://yohei0819.github.io"

databases:
  - name: recruit-db
    plan: free
    databaseName: recruit_portfolio
    user: recruit_user
